# Download base image ubuntu latest
FROM ubuntu:20.04

ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install sudo vim curl postgresql postgresql-contrib systemctl -y
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install nodejs wget

RUN mkdir app
COPY . ./app
RUN chmod 777 ./app/startup.sh

RUN cd ./app

CMD ["./app/startup.sh"]


EXPOSE 8080